### ISSUE TITLE
List of reasons from contrib/changes.html not compatible with mybb 1.8 (thread.js)

### ISSUE THREAD

**Issue by Neurovert** [lukasamd/MyBB-Mark_Edited_as_Unread#3]
Hi,
The following file:
https://github.com/lukasamd/MyBB-Mark_Edited_as_Unread/blob/master/contrib/changes.html
Is 3 years old - it's not compatible with mybb 1.8 - totally different jscripts/thread.js file.

Can you please update it, so these features would mybb 1.8?
If you won't update, then maybe remove this file or mark with mybb16 tag only. 
Thanks

**Comment by Eldenroot** [comment]
Is it still valid? @lukasamd

**Comment by lukasamd** [comment]
No, edit reason is build-in in MyBB 1.8 so it's old function and should be removed.
